// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutsourceRequestApp.Data;

#nullable disable

namespace OutsourceRequestApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OutsourceRequestApp.Models.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("OutsourceRequestApp.Models.ApproverRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleDisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApproverRoles");
                });

            modelBuilder.Entity("OutsourceRequestApp.Models.OutsourceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcessionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CostEnteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CostEnteredBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CostInhousePerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CostOutsourcePerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrawingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinanceComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinanceReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinanceReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JFComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("JFSignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JFSignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LJComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LJSignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LJSignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastReminderSentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MDComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MDSignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MDSignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MdComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MdReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MdReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPAPNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PpapRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("PpapRequiredLegacy")
                        .HasColumnType("bit");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestNumber")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SGComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SGSignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SGSignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SapDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SpecialPackingRequired")
                        .HasColumnType("bit");

                    b.Property<string>("SpecialPackingDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("OutsourceRequests");
                });

            modelBuilder.Entity("OutsourceRequestApp.Models.OutsourceRequestCostLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InhouseCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutsourceCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("OutsourceRequestCostLines");
                });

            modelBuilder.Entity("OutsourceRequestApp.Models.OutsourceRequestAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("OutsourceRequestAuditLogs");
                });

            modelBuilder.Entity("OutsourceRequestApp.Models.OutsourceRequestCostLine", b =>
                {
                    b.HasOne("OutsourceRequestApp.Models.OutsourceRequest", "Request")
                        .WithMany("CostLines")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("OutsourceRequestApp.Models.OutsourceRequestAuditLog", b =>
                {
                    b.HasOne("OutsourceRequestApp.Models.OutsourceRequest", "Request")
                        .WithMany("AuditLogs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("OutsourceRequestApp.Models.OutsourceRequest", b =>
                {
                    b.Navigation("CostLines");
                    b.Navigation("AuditLogs");
                });

#pragma warning restore 612, 618
        }
    }
}
